// client/src/components/LoginForm.tsx
import React, { useEffect } from 'react';
import { Button } from './Button';
import { InputField } from './InputField';
import { useForm } from 'react-hook-form';
import { useAuth } from '../hooks/auth.hook';

interface LoginFormProps {
  onLogin: () => void;
}

type LoginFormData = {
  email: string;
  password: string;
};

const LoginForm: React.FC<LoginFormProps> = ({ onLogin }) => {
  const {
    register,
    handleSubmit: handleReactHookFormSubmit,
    formState,
  } = useForm<LoginFormData>();

  const { login, user, error } = useAuth();

  useEffect(() => {
    if (user) {
      onLogin();
    }
  }, [user, onLogin]);

  const handleSubmit = handleReactHookFormSubmit(({ email, password }) => {
    login(email, password);
  });

  return (
    <div className="flex flex-col gap-4 w-[380px]">
      <h5 className="text-xl">Login</h5>
      <form noValidate className="flex flex-col gap-4" onSubmit={handleSubmit}>
        <InputField
          label="Email"
          data-cy="email"
          expand="full"
          type="email"
          errorMessage={formState.errors.email?.message as string}
          {...register('email', {
            required: 'Email is required',
            pattern: {
              value: /\S+@\S+\.\S+/,
              message: 'Email is not valid',
            },
          })}
        />

        <InputField
          label="Password"
          data-cy="password"
          expand="full"
          type="password"
          errorMessage={formState.errors.password?.message as string}
          {...register('password', {
            required: 'Password is required',
          })}
        />

        {error && <div className="text-red-500">{error}</div>}

        <Button expand="full">Sign in</Button>
      </form>
    </div>
  );
};

export default LoginForm;

// client-angular/src/app/components/login-form/login-form.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { catchError, of } from 'rxjs';
import { AuthService } from '../../../app/services/auth.service';
@Component({
  selector: 'app-login-form',
  templateUrl: 'login-form.component.html',
})
export class LoginFormComponent implements OnInit {
  constructor(
    private authService: AuthService
  ) {}

  @Output() onLogin = new EventEmitter();

  errorMessage?: string;

  loginForm = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required]),
  });

  ngOnInit(): void {}

  onSubmit() {
    if (this.loginForm.valid) {
      const creds = {
        username: this.loginForm.value.email!,
        password: this.loginForm.value.password!,
      };
      this.authService
        .login(creds.username, creds.password)
        .pipe(
          catchError((err: Error) => {
            this.errorMessage = err.message;
            return of(undefined);
          })
        )
        .subscribe((result) => {
          if (result) {
            this.onLogin.emit();
          }
        });
    }
  }
}

<div class="flex flex-col gap-4 w-[380px]">
  <h5 class="text-xl">Login</h5>
  <form
    [formGroup]="loginForm"
    (ngSubmit)="onSubmit()"
    #ngForm="ngForm"
    class="flex flex-col gap-4"
  >
    <app-input-field label="Email">
      <input
        app-text-input
        expand="full"
        type="email"
        formControlName="email"
        required
      />
      <div validation-errors>
        <div
          *ngIf="ngForm.submitted && loginForm.controls.email.errors?.['required']"
        >
          Email is required.
        </div>
        <div
          *ngIf="ngForm.submitted && loginForm.controls.email.errors?.['email']"
        >
          Email must be a valid email address.
        </div>
      </div>
    </app-input-field>

    <app-input-field label="Password">
      <input
        app-text-input
        expand="full"
        type="password"
        formControlName="password"
        required
      />
      <div
        validation-errors
        *ngIf="ngForm.submitted && loginForm.controls.password.errors?.['required']"
      >
        Password is required.
      </div>
    </app-input-field>

    <div *ngIf="errorMessage" validation-errors>
      {{ errorMessage }}
    </div>

    <app-button expand="full">Sign in</app-button>
  </form>
</div>
