// client-react/src/components/HeroForm.tsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Hero, HeroEditModel, Power } from '../models';
import { Button } from './Button';
import { InputField } from './InputField';
import { SelectField } from './SelectField';

interface HeroFormProps {
  hero?: Hero;
  powers: Power[];
  onSave: (hero: HeroEditModel, file?: File) => void;
}

type HeroFormData = {
  name: string;
  fans: number;
  saves: number;
  price: number;
  powers: number[];
};

const HeroForm: React.FC<HeroFormProps> = ({ hero, powers, onSave }) => {
  const [file, setFile] = useState<File>();
  const [imageUrl, setImageUrl] = useState<string>();

  const {
    register,
    handleSubmit: handleReactHookFormSubmit,
    formState,
  } = useForm<HeroFormData>();

  const handleSubmit = handleReactHookFormSubmit((heroFormData) => {
    const newHero: HeroEditModel = {
      id: hero?.id,
      name: heroFormData.name,
      price: heroFormData.price,
      fans: heroFormData.fans,
      saves: heroFormData.saves,
      powers: heroFormData.powers.map(x => Number(x)),
    };
    onSave(newHero, file);
  });

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newFile = event.target.files![0];
    if (newFile) {
      setFile(newFile);
      const reader = new FileReader();
      reader.readAsDataURL(newFile);
      reader.onload = () => {
        setImageUrl(reader.result as string);
      };
    }
  };

  return (
    <form noValidate className="flex flex-col gap-4" onSubmit={handleSubmit}>
      <InputField
        label="Name"
        defaultValue={hero?.name}
        type="text"
        errorMessage={formState.errors.name?.message as string}
        {...register('name', {
          required: 'Name is required',
          
        })}
      />
      <InputField
        label="Price"
        defaultValue={hero?.price}
        type="number"
        errorMessage={formState.errors.price?.message as string}
        {...register('price', {
          required: 'Price is required',
          valueAsNumber: true,
        })}
      />
      <InputField
        label="Fans"
        defaultValue={hero?.fans}
        type="number"
        errorMessage={formState.errors.fans?.message as string}
        {...register('fans', {
          required: 'Fans is required',
          valueAsNumber: true,
        })}
      />
      <InputField
        label="Saves"
        defaultValue={hero?.saves}
        type="number"
        errorMessage={formState.errors.saves?.message as string}
        {...register('saves', {
          required: 'Saves is required',
          valueAsNumber: true,
        })}
      />

      <SelectField
        defaultValue={hero?.powers.map((i) => i.id.toString())}
        label="Powers"
        multiple
        size={6}
        errorMessage={formState.errors.powers?.message as string}
        {...register('powers', {
          required: 'Powers is required',
          valueAsNumber: true,
        })}
      >
        {powers.map((power, i) => (
          <option value={power.id} key={i}>
            {power.name}
          </option>
        ))}
      </SelectField>
      <div>
        <label className="block mb-2 text-sm font-medium text-gray-500">
          Avatar
        </label>
        <div className="border border-dashed border-gray-500 relative block max-w-sm">
          <input
            accept="image/*"
            type="file"
            id="avatar"
            data-cy="avatarFile"
            className="cursor-pointer absolute block opacity-0 top-0 right-0 left-0 z-50 w-full h-full"
            onChange={handleFileChange}
          />
          {imageUrl ? (
            <img src={imageUrl} />
          ) : (
            <div className="text-center p-10 w-full h-full">
              <h4>
                Drop image here
                <br />
                or
              </h4>
              <p className="">Select image</p>
            </div>
          )}
        </div>
      </div>
      <Button className="max-w-[100px]">Submit</Button>
    </form>
  );
};

export default HeroForm;

// client-angular/src/app/components/hero-form/hero-form.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Hero, HeroEditModel, Power } from '../../services/models';

@Component({
  selector: 'app-hero-form',
  templateUrl: './hero-form.component.html',
})
export class HeroFormComponent implements OnInit {
  constructor() {}

  @Input('hero') hero?: Hero;
  @Input('powers') powers: Power[] = [];
  @Output() onSave = new EventEmitter<{
    hero: HeroEditModel;
    file?: File;
  }>();

  imageUrl: string = '';
  file?: File;

  heroForm = new FormGroup({
    name: new FormControl('', [Validators.required]),
    price: new FormControl(0, [Validators.required, Validators.min(1)]),
    fans: new FormControl(0, [Validators.required]),
    saves: new FormControl(0, [Validators.required]),
    powers: new FormControl<number[]>([], [Validators.required]),
  });

  async onSubmit() {
    if (this.heroForm.valid) {
      const hero: HeroEditModel = {
        id: this.hero?.id,
        name: this.heroForm.value.name!,
        price: Number(this.heroForm.value.price),
        fans: Number(this.heroForm.value.fans),
        saves: Number(this.heroForm.value.saves),
        powers: this.heroForm.value.powers!,
      };
      this.onSave.emit({
        hero: hero,
        file: this.file,
      });
    }
  }

  onFileChange(file: File) {
    if (file) {
      this.file = file;
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        this.imageUrl = reader.result as string;
      };
    }
  }

  ngOnInit(): void {
    if (this.hero) {
      const { id, avatarUrl, ...rest } = this.hero;
      this.heroForm.setValue({
        ...rest,
        powers: this.hero.powers.map((x) => x.id),
      });
    }
  }
}

<form
  [formGroup]="heroForm"
  (ngSubmit)="onSubmit()"
  #ngForm="ngForm"
  class="flex flex-col gap-4"
>
  <app-input-field label="Name">
    <input app-text-input type="text" formControlName="name" required />
    <div
      validation-errors
      *ngIf="ngForm.submitted && heroForm.controls.name.errors?.['required']"
    >
      Name is required.
    </div>
  </app-input-field>

  <app-input-field label="Price">
    <input app-text-input type="number" formControlName="price" required />
    <div validation-errors>
      <div
        *ngIf="ngForm.submitted && heroForm.controls.price.errors?.['required']"
      >
        Price is required.
      </div>
      <div *ngIf="ngForm.submitted && heroForm.controls.price.errors?.['min']">
        Price must be greater than 0.
      </div>
    </div>
  </app-input-field>

  <app-input-field label="Fans">
    <input app-text-input type="number" formControlName="fans" required />
    <div validation-errors>
      <div
        *ngIf="ngForm.submitted && heroForm.controls.fans.errors?.['required']"
      >
        Fans is required.
      </div>
      <div *ngIf="ngForm.submitted && heroForm.controls.fans.errors?.['min']">
        Fans must be greater than 0.
      </div>
    </div>
  </app-input-field>

  <app-input-field label="Saves">
    <input app-text-input type="number" formControlName="saves" required />
    <div validation-errors>
      <div
        *ngIf="ngForm.submitted && heroForm.controls.saves.errors?.['required']"
      >
        Saves is required.
      </div>
      <div *ngIf="ngForm.submitted && heroForm.controls.saves.errors?.['min']">
        Saves must be greater than 0.
      </div>
    </div>
  </app-input-field>

  <app-input-field label="Powers">
    <select
      app-text-input
      formControlName="powers"
      multiple
      size="6"
      class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-sm focus:ring-blue-500 focus:border-blue-500 block w-1/3 p-2.5"
    >
      <option *ngFor="let power of powers" [ngValue]="power.id">
        {{ power.name }}
      </option>
    </select>
    <div
      validation-errors
      *ngIf="ngForm.submitted && heroForm.controls.powers.errors?.['required']"
    >
      At least one power is required.
    </div>
  </app-input-field>

  <app-input-field label="Avatar">
    <div app-text-input class="border border-dashed border-gray-500 relative block max-w-sm">
      <input
        accept="image/*"
        type="file"
        id="avatar"
        class="cursor-pointer absolute block opacity-0 top-0 right-0 left-0 z-50 w-full h-full"
        #fileInput
        (change)="onFileChange(fileInput!.files![0])"
      />
      <div *ngIf="!imageUrl" class="text-center p-10 w-full h-full">
        <h4>
          Drop image here
          <br />or
        </h4>
        <p class="">Select files</p>
      </div>
      <img *ngIf="imageUrl" src="{{ imageUrl }}" />
    </div>
  </app-input-field>

  <app-button>Submit</app-button>
</form>
