// client-angular/src/app/components/alert-modal/alert-modal.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ModalService } from '../../services/modal.service';

@Component({
  selector: 'alert-modal',
  template: `
    <app-modal>
      <div class="flex flex-col gap-4 text-center">
        <div class="flex flex-col items-center text-sm text-gray-500">
          <h5 class="mb-1 text-xl font-medium text-gray-500">
            {{ message }}
          </h5>
        </div>

        <div class="flex gap-2 justify-end">
          <app-button type="outline" (click)="hideModal()">Ok</app-button>
        </div>
      </div>
    </app-modal>
  `,
})
export class AlertModalComponent implements OnInit {
  constructor(private modalService: ModalService) {}

  @Input() message!: string;
  ngOnInit(): void {}

  hideModal() {
    this.modalService.hide();
  }
}

// client/src/components/AlertModal.tsx
import React from 'react';
import { Button } from './Button';

interface AlertModalProps extends React.PropsWithChildren {
  onDismiss: () => void;
}

export const AlertModal: React.FC<AlertModalProps> = ({
  children,
  onDismiss,
}) => {
  return (
    <div className="flex flex-col gap-4 text-center">
      <div className="flex flex-col items-center text-sm text-gray-500">
        <h5 className="mb-1 text-xl font-medium text-gray-500">{children}</h5>
      </div>

      <div className="flex gap-2 justify-end">
        <Button color="outline" onClick={onDismiss}>
          Ok
        </Button>
      </div>
    </div>
  );
};
