// client-angular/src/app/components/confirm-hire-modal/confirm-hire-modal.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Hero } from '../../../app/services/models';
import { ModalService } from '../../services/modal.service';

@Component({
  selector: 'confirm-hire-modal',
  template: `
    <app-modal>
      <div class="flex flex-col gap-4 text-center">
        <h3 class="text-lg leading-6 font-medium text-gray-900">Hire Hero?</h3>

        <p class="text-sm text-gray-500">
          Hire this hero for {{ hero.price | currency }}?
        </p>
        <div class="flex flex-col items-center text-sm text-gray-500">
          <app-avatar class="text-center" [hero]="hero"></app-avatar>
          <h5 class="mb-1 text-xl font-medium text-gray-500">
            {{ hero.name }}
          </h5>
        </div>

        <div class="flex gap-2 justify-end">
          <app-button type="danger" (click)="onHire(hero)">Yes</app-button>
          <app-button type="outline" (click)="hideModal()">No</app-button>
        </div>
      </div>
    </app-modal>
  `,
})
export class ConfirmHireModalComponent implements OnInit {
  constructor(private modalService: ModalService) {}

  @Input() hero!: Hero;
  @Input() onHire!: any;

  ngOnInit(): void {}

  hideModal() {
    this.modalService.hide();
  }
}

// client/src/components/ConfirmHireModal.tsx
import React from 'react';
import { Hero } from '../models';
import { Avatar } from './Avatar';
import { Button } from './Button';

interface ConfirmHireModalProps extends React.PropsWithChildren {
  hero: Hero;
  onHire: () => void;
  onDismiss: () => void;
}

export const ConfirmHireModal: React.FC<ConfirmHireModalProps> = ({
  hero,
  onHire,
  onDismiss,
}) => {
  return (
    <div className="flex flex-col gap-4 text-center">
      <h3 className="text-lg leading-6 font-medium text-gray-900">
        Hire Hero?
      </h3>

      <p className="text-sm text-gray-500">Hire this hero for {hero.price}?</p>
      <div className="flex flex-col items-center text-sm text-gray-500">
        <Avatar className="text-center" hero={hero} />
        <h5 className="mb-1 text-xl font-medium text-gray-500">{hero.name}</h5>
      </div>

      <div className="flex gap-2 justify-end">
        <Button color="danger" onClick={onHire}>
          Yes
        </Button>
        <Button color="outline" onClick={onDismiss}>
          No
        </Button>
      </div>
    </div>
  );
};
