// client-angular/src/app/pages/layout/header.component.ts
import { Component, OnInit } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { Observable } from 'rxjs';
import { AppRoutingModule } from '../../../app/app-routing.module';
import { ComponentsModule } from '../../../app/components/components.module';
import { AuthService } from '../../../app/services/auth.service';
import { ModalService } from '../../../app/services/modal.service';
import { User } from '../../../app/services/models';
import { LoginModalComponent } from '../../components/login-modal/login-modal.component';

@Component({
  standalone: true,
  imports: [AppRoutingModule, ComponentsModule, BrowserModule],
  selector: 'app-header',
  template: `
    <header class="text-gray-500">
      <div class="flex justify-between items-center mx-auto max-w-6xl p-2">
        <div>
          <a routerLink="/"
            ><img src="/assets/images/cypress-logo.svg" alt="Cypress Logo"
          /></a>
        </div>
        <nav>
          <ul class="flex gap-8">
            <li *ngIf="user && user.isAdmin">
              <app-button type="primary" routerLink="/heroes/new"
                >Create New Hero</app-button
              >
            </li>
            <li>
              <app-button *ngIf="user" type="outline" (click)="logout()"
                >Logout</app-button
              >
              <app-button
                *ngIf="!user"
                type="outline"
                (click)="showLoginModal()"
                >Login</app-button
              >
            </li>
          </ul>
        </nav>
      </div>
    </header>
  `,
})
export class HeaderComponent implements OnInit {
  constructor(
    private modalService: ModalService,
    private authService: AuthService
  ) {}

  user?: User;

  ngOnInit(): void {
    this.authService.getUser().subscribe((u) => {
      this.user = u;
    });
  }

  showLoginModal() {
    this.modalService.show(LoginModalComponent);
  }

  logout() {
    this.authService.logout();
  }
}

// client/src/components/Header.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../hooks/auth.hook';
import { useModal } from '../hooks/modal.hook';
import { Button } from './Button';
import LoginForm from './LoginForm';

interface HeaderProps {}

const Header: React.FC<HeaderProps> = () => {
  const { setModal } = useModal();
  const { user, logout } = useAuth();
  return (
    <header className="text-gray-500">
      <div className="flex justify-between max-w-6xl">
        <div>
          <Link to="/">
            <img src="/images/cyheroes-logo.svg" alt="Cypress Heroes Logo" />
          </Link>
        </div>
        <nav>
          <ul className="flex gap-8">
            {user && user.isAdmin && (
              <li>
                <Link to="/heroes/new">
                  <Button color="primary">Create New Hero</Button>
                </Link>
              </li>
            )}
            <li>
              {user ? (
                <Button color="outline" onClick={logout}>
                  Logout
                </Button>
              ) : (
                <Button
                  color="outline"
                  onClick={() => {
                    setModal(<LoginForm onLogin={() => setModal(undefined)} />);
                  }}
                >
                  Login
                </Button>
              )}
            </li>
          </ul>
        </nav>
      </div>
    </header>
  );
};

export default Header;
